import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import heroAsset from "@/assets/livoara-hero.png.asset.json";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [
  { title: "Our Story — LIVOARA" }, { name: "description", content: "Discover LIVOARA's considered approach to beautiful everyday rituals." }, { property: "og:title", content: "Our Story — LIVOARA" }, { property: "og:description", content: "Thoughtful design for everyday beauty rituals." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: AboutPage });

function AboutPage() { return <div className="page-reveal"><section className="grid min-h-[72vh] lg:grid-cols-2"><div className="flex flex-col justify-center px-7 py-20 sm:px-12 lg:px-[9vw]"><p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Our story</p><h1 className="mt-6 font-display text-5xl leading-tight sm:text-7xl">A more beautiful way to get ready.</h1><p className="mt-7 max-w-lg leading-8 text-muted-foreground">LIVOARA was imagined around the quiet rituals that help us feel like ourselves. Our first piece brings together light, order, and portability in one considered form.</p></div><div className="min-h-[480px] overflow-hidden bg-secondary"><img src={heroAsset.url} alt="LIVOARA Travel Vanity in a warm, elegant setting" className="h-full w-full scale-[1.45] object-cover object-[70%_center]" /></div></section><section className="border-y border-border bg-muted/55 px-6 py-24 text-center"><p className="mx-auto max-w-3xl font-display text-3xl leading-relaxed sm:text-5xl">“We believe the objects used every day deserve the same care as the moments they hold.”</p><p className="mt-8 text-xs uppercase tracking-[0.18em] text-muted-foreground">Brand statement · editable</p></section><section className="mx-auto grid max-w-5xl gap-12 px-6 py-24 md:grid-cols-3"><Value n="01" title="Thoughtful" copy="Every detail begins with how it fits into a real routine."/><Value n="02" title="Beautiful" copy="Useful objects can still feel personal, tactile, and special."/><Value n="03" title="Enduring" copy="[Add verified material and durability commitments.]"/></section><section className="bg-secondary px-6 py-20 text-center"><h2 className="font-display text-4xl sm:text-5xl">Meet our first piece.</h2><Button asChild className="mt-8"><Link to="/product">Discover the vanity <ArrowRight className="size-4" /></Link></Button></section></div>; }
function Value({ n, title, copy }: { n: string; title: string; copy: string }) { return <div className="border-t border-border pt-6"><span className="text-xs text-muted-foreground">{n}</span><h2 className="mt-6 font-display text-3xl">{title}</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">{copy}</p></div>; }