import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Lightbulb, Luggage, PackageOpen, RotateCcw, ShieldCheck, Sparkles, Truck } from "lucide-react";
import heroAsset from "@/assets/livoara-hero.png.asset.json";
import referenceVanity from "@/assets/reference/livoara-reference-vanity.jpg.asset.json";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [
  { title: "About Us — LIVOARA" }, { name: "description", content: "Discover LIVOARA’s vision for organised living, thoughtful products, and better everyday experiences." }, { property: "og:title", content: "About Us — LIVOARA" }, { property: "og:description", content: "Organise, simplify, and elevate everyday living with LIVOARA." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: AboutPage });

function AboutPage() {
  return <div className="page-reveal">
    <section className="grid lg:grid-cols-2 lg:min-h-[480px] lg:max-h-[560px]">
      <div className="flex flex-col justify-center px-7 py-8 sm:px-12 lg:px-[8vw] lg:py-16"><p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">About LIVOARA</p><h1 className="mt-4 font-display text-3xl leading-tight sm:text-5xl lg:text-6xl">Better organised spaces. Better everyday experiences.</h1><p className="mt-5 max-w-xl text-sm leading-7 text-muted-foreground sm:text-base sm:leading-8">LIVOARA is a modern organised-living and lifestyle brand created to make everyday spaces feel calmer, smarter, and more inspiring. We create and curate smart, stylish, space-conscious products designed to transform spaces, simplify routines, and help people feel at their best.</p></div>
      <div className="relative h-[28vh] min-h-[200px] max-h-[280px] overflow-hidden bg-secondary sm:h-[32vh] lg:h-auto lg:max-h-none lg:min-h-0"><img src={heroAsset.url} alt="LIVOARA Travel Vanity in a warm, elegant setting" className="h-full w-full object-contain object-center sm:object-cover sm:object-[80%_center] lg:object-[72%_center]" /></div>
    </section>

    <section className="border-y border-border bg-muted/55 px-6 py-16 text-center sm:py-20"><p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Our belief</p><p className="mx-auto mt-6 max-w-3xl font-display text-3xl leading-relaxed sm:text-5xl">A better space can create a better day.</p><p className="mx-auto mt-7 max-w-2xl text-sm leading-7 text-muted-foreground">Organisation is not simply about putting things away. It is about creating an environment where everything has its place, routines become easier, and you have the freedom to focus on what matters.</p></section>

    <section className="mx-auto grid max-w-[1120px] gap-12 px-6 py-16 lg:grid-cols-2 lg:py-20">
      <StoryBlock eyebrow="Our vision" title="The ultimate destination for organised living." copy="We aspire to transform everyday spaces into clutter-free, beautifully designed environments that help people feel more confident, productive and at their best every day." />
      <StoryBlock eyebrow="Our mission" title="Simplify and elevate everyday living." copy="We create and curate smart, stylish and space-conscious products that turn cluttered personal spaces into organised, functional and inspiring environments. From intelligent LED mirrors and beauty organisers to storage, lifestyle and personalised products, we combine thoughtful design, practical innovation and timeless style." />
    </section>

    <section className="bg-secondary px-6 py-16 sm:px-10 sm:py-20"><div className="mx-auto max-w-[1120px]"><p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">What we design for</p><h2 className="mt-5 font-display text-4xl sm:text-5xl">Everyday problems, thoughtfully solved.</h2><div className="mt-10 grid gap-x-10 gap-y-8 sm:grid-cols-2 lg:grid-cols-4"><ProblemPoint icon={<PackageOpen className="size-5" />} title="Scattered essentials" copy="Daily items spread across drawers and pouches slow every routine down." /><ProblemPoint icon={<Lightbulb className="size-5" />} title="Unhelpful light" copy="Getting ready in poor room light makes even simple routines harder." /><ProblemPoint icon={<Luggage className="size-5" />} title="Too many pouches" copy="Travelling often means carrying several small bags for one routine." /><ProblemPoint icon={<Sparkles className="size-5" />} title="Cluttered spaces" copy="Busy surfaces make personal spaces feel stressful instead of calm." /></div></div></section>

    <section className="mx-auto max-w-[1120px] px-6 py-16 sm:px-10 sm:py-20"><p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">What guides us</p><h2 className="mt-5 font-display text-4xl sm:text-5xl">Our values.</h2><div className="mt-12 grid gap-x-10 gap-y-12 sm:grid-cols-2 lg:grid-cols-4"><Value n="01" title="Customer first" copy="Every product and experience should solve a genuine customer need."/><Value n="02" title="Thoughtful innovation" copy="Smarter ideas and design should solve real everyday problems."/><Value n="03" title="Functionality" copy="Every product should serve a purpose and make life easier."/><Value n="04" title="Timeless style" copy="Functionality should never come at the expense of aesthetics."/><Value n="05" title="Quality" copy="Products should deliver meaningful value and meet appropriate standards."/><Value n="06" title="Accessibility" copy="Good design and better organisation should feel attainable."/><Value n="07" title="Improvement" copy="We listen, learn and continually improve products and service."/><Value n="08" title="Transparency" copy="We communicate honestly about products, pricing and policies."/></div></section>

    <section className="grid border-y border-border lg:grid-cols-2"><div className="relative h-[40vh] min-h-[260px] overflow-hidden lg:h-auto lg:min-h-[420px]"><img src={referenceVanity.url} alt="LIVOARA Travel Vanity organised and ready for everyday use" className="h-full w-full object-cover" /></div><div className="flex flex-col justify-center gap-10 px-7 py-12 sm:px-12 lg:px-[8vw] lg:py-20"><StoryBlock eyebrow="Why choose us" title="Because everyday products should do more." copy="We look beyond simply selling products. We search for thoughtful solutions that make better use of space, simplify routines, and add style to everyday living. Every addition is selected with one question in mind: will this make everyday life better?" /><StoryBlock eyebrow="Our product philosophy" title="Purpose, practicality, and timeless style." copy="Every product should solve a genuine need, serve a clear purpose, and make daily life easier. We believe thoughtful innovation and useful design should feel accessible without compromising the way a product looks or feels." /></div></section>

    <section className="mx-auto grid max-w-[1120px] gap-12 px-6 py-16 lg:grid-cols-2 lg:py-20"><StoryBlock eyebrow="Our future" title="More than what we sell today." copy="What begins with smart beauty and organisation is designed to grow across women’s and men’s lifestyle, beauty and grooming, personal organisation, storage, gifting, personalised products, and Print-on-Demand—always connected by one philosophy." /><StoryBlock eyebrow="Our customer promise" title="A better space can create a better day." copy="Whether you are getting ready, organising personal belongings, grooming, working, travelling, gifting, or enjoying your space, our aim is to make everyday life a little more effortless through clear information, practical value, and attentive service." /></section>

    <section className="border-y border-border bg-muted/55 px-6 py-14 sm:px-10"><div className="mx-auto grid max-w-[1120px] gap-8 sm:grid-cols-2 lg:grid-cols-4"><TrustPoint icon={<Truck className="size-5" />} title="Fast shipping" copy="Estimated timelines are shown at checkout." /><TrustPoint icon={<RotateCcw className="size-5" />} title="Easy returns" copy="7-day return request window as per our policy." /><TrustPoint icon={<ShieldCheck className="size-5" />} title="Secure payments" copy="Trusted payment options at checkout." /><TrustPoint icon={<Sparkles className="size-5" />} title="Thoughtful design" copy="Products selected for purpose, quality and style." /></div></section>

    <section className="mx-auto max-w-[1120px] px-6 py-16 sm:px-10"><p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Business identity</p><h2 className="mt-5 font-display text-4xl">Built by ARINJJOY VENTURES.</h2><div className="mt-8 grid gap-8 border-y border-border py-8 text-sm leading-7 text-muted-foreground sm:grid-cols-2"><p><strong className="text-foreground">Registered address</strong><br />Kalinga Nagar, Ghatikia<br />Bhubaneswar, Odisha – 751003</p><p><strong className="text-foreground">GSTIN</strong><br />21ACMFA2803PIZE<br /><a className="text-foreground underline underline-offset-4" href="mailto:hello@livoara.in">hello@livoara.in</a></p></div></section>

    <section className="px-6 py-16 text-center sm:py-20"><h2 className="font-display text-4xl sm:text-5xl">Explore thoughtful organisation.</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-7 text-muted-foreground">Products designed to make your spaces—and your everyday life—better.</p><Button asChild className="mt-8"><Link to="/product">Explore our collection <ArrowRight className="size-4" /></Link></Button></section>
  </div>;
}

function StoryBlock({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <article className="border-t border-border pt-7"><p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">{eyebrow}</p><h2 className="mt-5 max-w-lg font-display text-3xl leading-tight sm:text-4xl">{title}</h2><p className="mt-5 max-w-xl text-sm leading-7 text-muted-foreground">{copy}</p></article>; }
function Value({ n, title, copy }: { n: string; title: string; copy: string }) { return <article className="border-t border-border pt-6"><span className="text-xs text-muted-foreground">{n}</span><h3 className="mt-5 font-display text-2xl">{title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{copy}</p></article>; }
function ProblemPoint({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <article className="flex flex-col gap-3 border-t border-border pt-6"><span className="grid size-10 place-items-center rounded-full border border-border bg-background text-accent">{icon}</span><h3 className="font-display text-xl">{title}</h3><p className="text-sm leading-7 text-muted-foreground">{copy}</p></article>; }
function TrustPoint({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <div className="flex items-start gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-full border border-border bg-background text-accent">{icon}</span><div><p className="text-sm font-medium">{title}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{copy}</p></div></div>; }
