import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { EditorialPage } from "@/components/editorial-page";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/contact")({ head: () => ({ meta: [
  { title: "Contact Us — LIVOARA" }, { name: "description", content: "Contact LIVOARA for product and order support." }, { property: "og:title", content: "Contact Us — LIVOARA" }, { property: "og:description", content: "We would love to hear from you." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: ContactPage });

function ContactPage() { const [sent, setSent] = useState(false); return <EditorialPage eyebrow="Customer care" title="We’re here to help." intro="For product, order, delivery, return, exchange, or other questions, contact our customer-care team. We aim to respond to emails within two business working days."><div className="grid gap-14 lg:grid-cols-[1.4fr_.6fr]"><form className="grid gap-5" onSubmit={(e) => { e.preventDefault(); setSent(true); }}><Field id="name" label="Name" /><Field id="email" label="Email" type="email" /><div><label htmlFor="topic" className="mb-2 block text-xs uppercase tracking-[0.14em]">Topic</label><select id="topic" className="min-h-12 w-full border border-input bg-background px-4"><option>Product question</option><option>Order support</option><option>Return or exchange</option><option>Press & partnerships</option><option>Other</option></select></div><div><label htmlFor="message" className="mb-2 block text-xs uppercase tracking-[0.14em]">Message</label><textarea id="message" required rows={6} className="w-full border border-input bg-background p-4 outline-none focus:ring-2 focus:ring-ring" /></div><Button type="submit" className="w-fit">Send message</Button>{sent && <p role="status" className="border-l-2 border-accent pl-4 text-sm text-muted-foreground">Thank you. For immediate assistance, email hello@livoara.in with your order number where applicable.</p>}</form><aside className="border-t border-border pt-6"><h2 className="font-display text-2xl">Business details</h2><dl className="mt-5 space-y-5 text-sm leading-7"><Detail term="Legal business name" value="ARINJJOY VENTURES" /><Detail term="Brand / trade name" value="LIVOARA" /><Detail term="GSTIN" value="21ACMFA2803PIZE" /><Detail term="Registered address" value="Kalinga Nagar, Ghatikia, Bhubaneswar, Odisha – 751003" /><Detail term="Support email" value="hello@livoara.in" /><Detail term="Website" value="www.livoara.in" /><Detail term="Customer support" value="Email support is available at hello@livoara.in" /><Detail term="Customer support hours" value="10 AM to 1 PM" /></dl><p className="mt-7 border-t border-border pt-5 text-sm leading-7 text-muted-foreground">For order-related queries, keep your order number and the email or phone number used to place the order ready.</p></aside></div></EditorialPage>; }
function Field({ id, label, type = "text" }: { id: string; label: string; type?: string }) { return <div><label htmlFor={id} className="mb-2 block text-xs uppercase tracking-[0.14em]">{label}</label><input id={id} type={type} required className="min-h-12 w-full border border-input bg-background px-4 outline-none focus:ring-2 focus:ring-ring" /></div>; }
function Detail({ term, value }: { term: string; value: string }) { return <div><dt className="text-xs uppercase tracking-[0.12em] text-muted-foreground">{term}</dt><dd className="mt-1">{value}</dd></div>; }