import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { EditorialPage } from "@/components/editorial-page";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/contact")({ head: () => ({ meta: [
  { title: "Contact Us — LIVOARA" }, { name: "description", content: "Contact LIVOARA for product and order support." }, { property: "og:title", content: "Contact Us — LIVOARA" }, { property: "og:description", content: "We would love to hear from you." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: ContactPage });

function ContactPage() { const [sent, setSent] = useState(false); return <EditorialPage eyebrow="Get in touch" title="We’re here to help." intro="Questions about LIVOARA, your order, or a future gift? Leave us a note."><div className="grid gap-14 lg:grid-cols-[1.4fr_.6fr]"><form className="grid gap-5" onSubmit={(e) => { e.preventDefault(); setSent(true); }}><Field id="name" label="Name" /><Field id="email" label="Email" type="email" /><div><label htmlFor="topic" className="mb-2 block text-xs uppercase tracking-[0.14em]">Topic</label><select id="topic" className="min-h-12 w-full border border-input bg-background px-4"><option>Product question</option><option>Order support</option><option>Press & partnerships</option><option>Other</option></select></div><div><label htmlFor="message" className="mb-2 block text-xs uppercase tracking-[0.14em]">Message</label><textarea id="message" required rows={6} className="w-full border border-input bg-background p-4 outline-none focus:ring-2 focus:ring-ring" /></div><Button type="submit" className="w-fit">Send message</Button>{sent && <p role="status" className="border-l-2 border-accent pl-4 text-sm text-muted-foreground">Thanks—this preview form is complete. Connect your inbox before launch to receive messages.</p>}</form><aside className="border-t border-border pt-6"><h2 className="font-display text-2xl">Contact details</h2><p className="mt-5 text-sm leading-7 text-muted-foreground">Email: [add support email]<br />Hours: [add support hours]<br />Response time: [add verified timeframe]</p></aside></div></EditorialPage>; }
function Field({ id, label, type = "text" }: { id: string; label: string; type?: string }) { return <div><label htmlFor={id} className="mb-2 block text-xs uppercase tracking-[0.14em]">{label}</label><input id={id} type={type} required className="min-h-12 w-full border border-input bg-background px-4 outline-none focus:ring-2 focus:ring-ring" /></div>; }