import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Check, CirclePlay, Gem, Headphones, LayoutGrid, Luggage, RotateCcw, ShieldCheck, Star, SunMedium, Truck } from "lucide-react";
import type { ReactNode } from "react";
import heroAsset from "@/assets/livoara-hero.png.asset.json";
import whiteSunlight from "@/assets/reference/livoara-product-white-sunlight.jpg";
import productDetail from "@/assets/reference/livoara-product-detail.jpg";
import pinkStacked from "@/assets/reference/livoara-product-pink-stacked.jpg";
import categoryWomen from "@/assets/reference/livoara-category-women.jpg";
import categoryMen from "@/assets/reference/livoara-category-men.jpg";
import categoryBeauty from "@/assets/reference/livoara-category-beauty.jpg";
import categoryLifestyle from "@/assets/reference/livoara-category-lifestyle.jpg";
import categoryGifts from "@/assets/reference/livoara-category-gifts.jpg";
import categoryAccessories from "@/assets/reference/livoara-category-accessories.jpg";
import categoryPod from "@/assets/reference/livoara-category-pod.jpg";
import problemScattered from "@/assets/livoara-problem-scattered.jpg";
import problemHidden from "@/assets/livoara-problem-hidden.jpg";
import routineVideo from "@/assets/livoara-use-routine.mp4.asset.json";
import womanOrganise from "@/assets/livoara-woman-organise-correct.jpg";
import womanRoutine from "@/assets/livoara-woman-routine-correct.jpg";
import womanTravel from "@/assets/livoara-woman-travel-correct.jpg";
import womanOrganiseVideo from "@/assets/livoara-correct-organise.mp4.asset.json";
import womanRoutineVideo from "@/assets/livoara-correct-routine.mp4.asset.json";
import womanTravelVideo from "@/assets/livoara-correct-travel.mp4.asset.json";
import editorialBanner from "@/assets/livoara-editorial-banner-correct.jpg";
import reviewerAnanya from "@/assets/reviewer-ananya.jpg";
import reviewerRiya from "@/assets/reviewer-riya.jpg";
import reviewerMeher from "@/assets/reviewer-meher.jpg";
import reviewerKavya from "@/assets/reviewer-kavya.jpg";
import reviewerIsha from "@/assets/reviewer-isha.jpg";
import reviewerNeha from "@/assets/reviewer-neha.jpg";
import reviewerSana from "@/assets/reviewer-sana.jpg";
import reviewerAashi from "@/assets/reviewer-aashi.jpg";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "LIVOARA — Made for Every Moment" },
    { name: "description", content: "Discover the LIVOARA travel vanity, a luminous beauty companion thoughtfully designed for travel, gifting, and everyday rituals." },
    { property: "og:title", content: "LIVOARA — Made for Every Moment" },
    { property: "og:description", content: "A luminous vanity, thoughtful organizer, and travel companion—beautifully designed as one." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ]}),
  component: HomePage,
});

function HomePage() {
  return <div className="page-reveal max-w-full overflow-x-clip">
    <section aria-label="Made for every moment" className="relative bg-secondary">
      <h1 className="sr-only">LIVOARA — Made for every moment.</h1>
      <Link to="/product" className="block" aria-label="Shop the LIVOARA Travel Vanity">
        <picture><img src={heroAsset.url} alt="LIVOARA illuminated travel vanity with mirror, beauty products and jewellery" className="h-[52dvh] min-h-[350px] max-h-[520px] w-full object-cover object-[68%_center] sm:h-auto sm:min-h-0 sm:max-h-none sm:object-contain" /></picture>
      </Link>
      <div className="bg-secondary px-5 py-5 sm:hidden"><Button asChild className="w-full"><Link to="/product">Shop Now <ArrowRight className="size-4" /></Link></Button></div>
    </section>

    <section aria-label="Product highlights" className="border-y border-border bg-background"><div className="mx-auto grid max-w-[1120px] grid-cols-2 divide-x divide-y divide-border sm:grid-cols-4 sm:divide-y-0"><FeatureIcon icon={<LayoutGrid />} title="Organised storage" /><FeatureIcon icon={<SunMedium />} title="LED mirror" /><FeatureIcon icon={<Luggage />} title="Travel-friendly" /><FeatureIcon icon={<Gem />} title="Stylish & modern" /></div></section>

    <section className="bg-muted/50 px-6 py-10 sm:px-10 lg:py-14"><div className="mx-auto grid max-w-[1120px] gap-8 md:grid-cols-[.88fr_1.12fr] md:items-center lg:gap-14"><div><p className="text-[10px] uppercase tracking-[0.22em] text-accent">Everyday problems, considered</p><h2 className="mt-3 font-display text-4xl sm:text-5xl">A smarter way to get ready.</h2><p className="mt-4 max-w-md text-sm leading-7 text-muted-foreground">LIVOARA brings your mirror, light and organised storage together, so your everyday routine feels clear and considered.</p><ul className="mt-6 grid gap-3 text-sm sm:grid-cols-2 md:grid-cols-1 lg:grid-cols-2"><Benefit text="Everything visible at a glance" /><Benefit text="Light where you need it" /><Benefit text="One case from home to travel" /><Benefit text="Less clutter, calmer routine" /></ul><Button asChild variant="outline" className="mt-7"><Link to="/product">Discover LIVOARA <ArrowRight className="size-4" /></Link></Button></div><div className="relative aspect-[4/3] overflow-hidden bg-secondary"><video src={routineVideo.url} poster={whiteSunlight} muted loop playsInline controls preload="metadata" className="h-full w-full object-cover" aria-label="LIVOARA illuminated mirror in an everyday routine" /><span className="pointer-events-none absolute left-4 top-4 grid size-10 place-items-center bg-background/90 text-accent" aria-hidden="true"><CirclePlay className="size-5" /></span></div></div></section>

    <section className="mx-auto max-w-[1120px] px-6 py-11 sm:px-10 lg:py-14">
      <h2 className="font-display text-4xl sm:text-5xl">Designed for your daily ritual.</h2><p className="mt-3 max-w-lg text-sm leading-7 text-muted-foreground">Every detail is made to keep your makeup organised, beautifully lit and easy to reach.</p>
      <div className="mt-7 grid gap-x-8 gap-y-8 md:grid-cols-2"><Feature image={whiteSunlight} title="LED mirror for a clear finish" text="Get ready with bright, even light wherever you are." /><Feature image={categoryLifestyle} title="Room for your everyday essentials" text="Keep palettes, brushes, skincare and accessories together." /><Feature image={productDetail} title="Smart compartments" text="Dedicated spaces make every product easy to see and pick." /><Feature image={pinkStacked} title="Compact, elegant and portable" text="Bring your vanity routine from bedroom to suitcase with ease." /></div>
    </section>

    <section className="bg-secondary px-6 py-11 sm:px-10 lg:py-14"><div className="mx-auto max-w-[1120px]"><div className="grid gap-4 md:grid-cols-[.85fr_1.15fr] md:items-end"><div><p className="text-[10px] uppercase tracking-[0.22em] text-accent">Problem to solution</p><h2 className="mt-3 font-display text-4xl sm:text-5xl">Sound familiar?</h2></div><p className="max-w-xl text-sm leading-7 text-muted-foreground">Two everyday frustrations, followed by the LIVOARA way to get ready.</p></div><div className="mt-7 grid grid-cols-2 gap-3 md:grid-cols-4"><Problem image={problemScattered} label="Problem" title="Makeup everywhere" text="Essentials spread across the dresser." /><Problem image={problemHidden} label="Problem" title="Always searching" text="Small favourites hidden at the bottom." /><Problem image={categoryWomen} label="LIVOARA solution" title="Everything in its place" text="The LIVOARA organiser keeps essentials together." /><Problem image={categoryBeauty} label="LIVOARA solution" title="Light where you need it" text="The LIVOARA illuminated mirror supports each detail." /></div></div></section>

    <section className="border-y border-border px-6 py-9 sm:px-10 lg:py-11"><div className="mx-auto max-w-[1120px]"><div className="grid gap-3 md:grid-cols-[1fr_auto] md:items-end"><div><p className="text-[10px] uppercase tracking-[0.22em] text-accent">See it in your routine</p><h2 className="mt-2 font-display text-4xl sm:text-5xl">Designed to be used, beautifully.</h2></div><p className="max-w-sm text-sm leading-6 text-muted-foreground">Real-life moments show how light, storage and portability come together.</p></div><div className="mt-6 grid gap-4 md:grid-cols-3"><UseVideo src={womanOrganiseVideo.url} poster={womanOrganise} title="Organise your essentials" text="Keep everyday beauty pieces visible and together." /><UseVideo src={womanRoutineVideo.url} poster={womanRoutine} title="Create your light" text="Bring an illuminated mirror into the getting-ready moment." /><UseVideo src={womanTravelVideo.url} poster={womanTravel} title="Pack one considered case" text="Move from dresser to travel with one compact format." /></div></div></section>

    <section className="mx-auto max-w-[1120px] px-6 py-11 sm:px-10 lg:py-14"><p className="text-[10px] uppercase tracking-[0.22em] text-accent">Collection</p><h2 className="mt-3 font-display text-4xl sm:text-5xl">Future Categories</h2><div className="mt-7 grid grid-cols-2 gap-4 md:grid-cols-4"><Category image={categoryWomen} label="Women" /><Category image={categoryMen} label="Men" /><Category image={categoryBeauty} label="Beauty" /><Category image={categoryLifestyle} label="Lifestyle" /><Category image={categoryGifts} label="Gifts" /><Category image={categoryAccessories} label="Accessories" /><Category image={categoryPod} label="POD" /><Category image={pinkStacked} label="Travel Vanity" /></div></section>

    <section className="relative min-h-[300px] overflow-hidden bg-secondary sm:min-h-[380px]"><img src={editorialBanner} alt="Open blush pink LIVOARA travel vanity with illuminated mirror and organised tray" width={1600} height={608} className="absolute inset-0 h-full w-full object-cover object-[66%_center]" loading="lazy" /><div className="absolute inset-0 bg-background/10" aria-hidden="true" /><div className="relative z-10 mx-auto flex min-h-[300px] max-w-[1120px] items-center px-6 py-9 sm:min-h-[380px] sm:px-10"><div className="max-w-[34rem]"><h2 className="font-display text-4xl leading-tight sm:text-5xl">Designed for your everyday,<br className="hidden sm:block" /> beautiful wherever you go.</h2><Button asChild className="mt-5"><Link to="/product">Shop Now <ArrowRight className="size-4" /></Link></Button></div><p className="absolute bottom-7 right-6 max-w-[9rem] rotate-[-5deg] text-right font-display text-xl italic sm:bottom-10 sm:right-10 sm:text-3xl">Compact.<br />Chic.<br />Yours.</p></div></section>

    <section className="px-6 py-11 sm:px-10 lg:py-14"><div className="mx-auto max-w-[1120px]"><p className="text-[10px] uppercase tracking-[0.22em] text-accent">Problem vs solution · us vs them</p><h2 className="mt-3 font-display text-4xl sm:text-5xl">A better way to get ready.</h2><p className="mt-3 max-w-lg text-sm leading-7 text-muted-foreground">See how a dedicated LED makeup box creates a more considered routine than scattered storage.</p><div className="-mx-6 mt-6 overflow-x-auto px-6 pb-3 sm:-mx-10 sm:px-10 md:mx-0 md:px-0"><table className="w-full min-w-[720px] border-collapse text-left text-xs"><thead><tr className="border-b border-border text-[9px] uppercase tracking-[0.17em]"><th className="px-4 py-4 font-medium"></th><th className="px-4 py-4 text-center font-medium">Loose on a vanity</th><th className="px-4 py-4 text-center font-medium">Generic organiser</th><th className="bg-secondary px-4 py-4 text-center font-medium text-accent">LIVOARA</th></tr></thead><tbody><CompareRow label="Organised storage" loose="Scattered" generic="General storage" livoara="Dedicated compartments" /><CompareRow label="Mirror lighting" loose="Separate mirror" generic="Usually separate" livoara="Illuminated mirror" /><CompareRow label="Getting-ready format" loose="Multiple items" generic="Storage focused" livoara="Mirror and storage together" /><CompareRow label="Travel format" loose="Separate pouches" generic="Varies by design" livoara="Compact vanity case" /><CompareRow label="Launch price" loose="Not applicable" generic="Varies" livoara="From ₹1,499" /></tbody></table></div></div></section>

    <section className="bg-muted/70 px-6 py-11 sm:px-10 lg:py-14"><div className="mx-auto max-w-[1120px]"><div className="grid gap-4 md:grid-cols-[1fr_auto] md:items-end"><div><p className="text-[10px] uppercase tracking-[0.22em] text-accent">Illustrative customer stories</p><h2 className="mt-3 max-w-xl font-display text-4xl sm:text-5xl">Thoughtful details, noticed in real routines.</h2></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><span className="flex gap-0.5" aria-hidden="true">{Array.from({ length: 5 }).map((_, index) => <Star key={index} className="size-4" />)}</span><span>Verified ratings added after collection</span></div></div><div className="-mx-6 mt-7 flex snap-x snap-mandatory gap-4 overflow-x-auto px-6 pb-3 sm:-mx-10 sm:px-10 lg:mx-0 lg:grid lg:grid-cols-4 lg:px-0"><ReviewCard image={reviewerAnanya} quote="The kind of organised setup I would want beside me every morning." name="Sample feedback · Ananya" /><ReviewCard image={reviewerRiya} quote="Mirror and storage together feels simpler than carrying separate pieces." name="Sample feedback · Riya" /><ReviewCard image={reviewerMeher} quote="It looks considered enough to keep out and compact enough to pack." name="Sample feedback · Meher" /><ReviewCard image={reviewerKavya} quote="Seeing everything in one place would make busy mornings feel easier." name="Sample feedback · Kavya" /><ReviewCard image={reviewerIsha} quote="The illuminated mirror is the detail I would use every single day." name="Sample feedback · Isha" /><ReviewCard image={reviewerNeha} quote="A neat case like this would keep my dressing area much calmer." name="Sample feedback · Neha" /><ReviewCard image={reviewerSana} quote="One compact vanity makes much more sense for weekend travel." name="Sample feedback · Sana" /><ReviewCard image={reviewerAashi} quote="The structured format feels polished without making the routine complicated." name="Sample feedback · Aashi" /></div></div></section>

    <section className="border-y border-border px-6 py-11 sm:px-10 lg:py-14"><div className="mx-auto max-w-2xl"><p className="text-center text-[10px] uppercase tracking-[0.22em] text-accent">Helpful details</p><h2 className="mt-3 text-center font-display text-4xl sm:text-5xl">Questions, answered.</h2><div className="mt-6 border-t border-border"><Faq question="What can I store in the LED makeup box?" answer="It is designed to organise everyday makeup, brushes, skincare, jewellery, and other small beauty essentials. Fit depends on the size and shape of each item." open /><Faq question="How does the illuminated mirror work?" answer="Use the controls and power instructions supplied with your product. Please read the product label and enclosed guide before first use." /><Faq question="How long does delivery take?" answer="The estimated delivery timeline and any applicable shipping charge are shown at checkout for your location. Tracking is shared after dispatch where available." /><Faq question="What if my order arrives damaged or incorrect?" answer="Email hello@livoara.in within 7 calendar days of delivery. A clear, continuous unboxing video is required so our team can assess the request under the Shipping & Returns Policy." /></div></div></section>

    <section className="relative overflow-hidden bg-secondary text-foreground"><img src={whiteSunlight} alt="" className="absolute inset-0 h-full w-full object-cover opacity-20" aria-hidden="true" /><div className="absolute inset-0 bg-secondary/90" aria-hidden="true" /><div className="relative z-10 mx-auto max-w-[1120px] px-6 py-12 sm:px-10 lg:py-16"><div className="grid gap-7 md:grid-cols-[1fr_auto] md:items-end"><div><p className="text-[10px] uppercase tracking-[0.22em] text-accent">Your everyday vanity</p><h2 className="mt-3 max-w-xl font-display text-4xl sm:text-5xl">Give your beauty routine<br />the light it deserves.</h2></div><Button asChild size="lg"><Link to="/product">Shop Now <ArrowRight className="size-4" /></Link></Button></div><div className="mt-9 grid grid-cols-2 border border-border bg-background/65 sm:grid-cols-4"><TrustItem icon={<Truck />} title="Shipping" text="Timeline at checkout" /><TrustItem icon={<RotateCcw />} title="Easy returns" text="7-day request window" /><TrustItem icon={<ShieldCheck />} title="Secure payments" text="Protected options" /><TrustItem icon={<Headphones />} title="Customer care" text="hello@livoara.in" /></div></div></section>
  </div>;
}

function FeatureIcon({ icon, title }: { icon: ReactNode; title: string }) { return <div className="flex min-h-24 items-center justify-center gap-3 px-3 py-5 text-center sm:min-h-28 sm:flex-col sm:gap-2 [&>svg]:size-5 [&>svg]:shrink-0 [&>svg]:text-accent"><>{icon}</><span className="text-xs font-medium">{title}</span></div>; }
function Benefit({ text }: { text: string }) { return <li className="flex items-center gap-2"><span className="grid size-5 shrink-0 place-items-center bg-secondary text-accent"><Check className="size-3" /></span>{text}</li>; }
function Feature({ image, title, text }: { image: string; title: string; text: string }) { return <article><div className="aspect-[1.35/1] overflow-hidden bg-background"><img src={image} alt={title} className="h-full w-full object-cover" loading="lazy" /></div><h3 className="mt-4 font-display text-2xl">{title}</h3><p className="mt-1.5 text-xs leading-6 text-muted-foreground">{text}</p></article>; }
function Problem({ image, label, title, text }: { image: string; label: "Problem" | "LIVOARA solution"; title: string; text: string }) { return <article className="bg-background"><div className="relative aspect-square overflow-hidden"><img src={image} alt={title} width={1088} height={1360} className="h-full w-full object-cover" loading="lazy" /><span className="absolute left-3 top-3 bg-background/90 px-2.5 py-1 text-[9px] font-medium uppercase tracking-[0.16em] text-accent">{label}</span></div><div className="p-4"><h3 className="font-display text-lg">{title}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{text}</p></div></article>; }
function UseVideo({ src, poster, title, text }: { src: string; poster: string; title: string; text: string }) { return <article><div className="group relative aspect-[3/4] overflow-hidden bg-secondary"><video src={src} poster={poster} muted loop playsInline controls preload="metadata" className="h-full w-full object-cover" aria-label={`${title} product use video`} /><span className="pointer-events-none absolute left-3 top-3 grid size-9 place-items-center bg-background/90 text-accent group-has-[video:playing]:opacity-0" aria-hidden="true"><CirclePlay className="size-5" /></span></div><h3 className="mt-3 font-display text-xl">{title}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{text}</p></article>; }
function Category({ image, label }: { image: string; label: string }) { return <article><div className="aspect-square overflow-hidden bg-secondary"><img src={image} alt={`${label} category`} className="h-full w-full object-cover" loading="lazy" /></div><div className="mt-2.5 flex items-center justify-between"><h3 className="font-display text-base">{label}</h3><span className="text-accent">↗</span></div></article>; }
function CompareRow({ label, loose, generic, livoara }: { label: string; loose: string; generic: string; livoara: string }) { return <tr className="border-b border-border"><th className="px-4 py-4 font-medium">{label}</th><td className="px-4 py-4 text-center text-muted-foreground">{loose}</td><td className="px-4 py-4 text-center text-muted-foreground">{generic}</td><td className="bg-muted px-4 py-4 text-center font-medium text-accent">{livoara}</td></tr>; }
function ReviewCard({ image, quote, name }: { image: string; quote: string; name: string }) { return <article className="w-[78vw] max-w-[18rem] shrink-0 snap-start border border-border bg-background p-4 lg:w-auto lg:max-w-none"><div className="flex items-center gap-3"><img src={image} alt="Illustrative customer portrait" width={816} height={816} className="size-12 shrink-0 rounded-full object-cover" loading="lazy" /><div><p className="text-xs font-medium">{name}</p><div className="mt-1 flex gap-0.5 text-muted-foreground" aria-label="Verified rating not yet available">{Array.from({ length: 5 }).map((_, index) => <Star key={index} className="size-3" />)}</div></div></div><blockquote className="mt-4 font-display text-base leading-snug">“{quote}”</blockquote><p className="mt-4 border-t border-border pt-3 text-[9px] uppercase tracking-[0.14em] text-muted-foreground">Illustrative story · rating pending verification</p></article>; }
function Faq({ question, answer, open = false }: { question: string; answer: string; open?: boolean }) { return <details open={open} className="group border-b border-border py-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 text-sm font-medium"><span>{question}</span><span className="text-lg transition-transform group-open:rotate-45">+</span></summary><p className="max-w-xl pt-3 text-xs leading-6 text-muted-foreground">{answer}</p></details>; }
function TrustItem({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <div className="flex min-h-28 flex-col items-center justify-center border-b border-r border-border p-4 text-center last:border-r-0 sm:border-b-0 [&>svg]:size-5 [&>svg]:text-accent"><>{icon}</><p className="mt-2 text-xs font-medium">{title}</p><p className="mt-1 text-[10px] text-muted-foreground">{text}</p></div>; }