import { createFileRoute } from "@tanstack/react-router";
import { CopySection, EditorialPage } from "@/components/editorial-page";

const description = "Read LIVOARA's privacy policy and learn how customer information is handled.";

export const Route = createFileRoute("/privacy")({
  head: () => ({ meta: [{ title: "Privacy Policy — LIVOARA" }, { name: "description", content: description }, { property: "og:title", content: "Privacy Policy — LIVOARA" }, { property: "og:description", content: description }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return <EditorialPage eyebrow="Policies & customer care" title="Privacy Policy" intro="LIVOARA respects your privacy and is committed to handling personal information responsibly. This policy explains what we may collect, why we collect it, how it may be used or shared, and the choices available to you.">
    <CopySection title="Policy status"><p>Effective date: 14 September 2026. This policy may be updated as our services and legal requirements evolve.</p></CopySection>
    <CopySection title="1. Information we may collect"><PolicyList items={["Name and contact details such as email address, mobile number, and delivery or billing address.", "Order and transaction details, including products purchased, order value, and order status.", "Payment-related information required to process transactions. Payment credentials are generally processed by the relevant payment gateway rather than stored directly by LIVOARA.", "Account information where customer accounts are created.", "Customer-service communications and information voluntarily provided in enquiries, complaints, reviews, or support requests.", "Technical information such as IP address, browser or device information, pages viewed, approximate usage information, and cookies or related technologies.", "Marketing preferences and interactions where appropriate consent has been provided or where otherwise permitted."]} /></CopySection>
    <CopySection title="2. How we use information"><PolicyList items={["Process and fulfil orders.", "Provide shipping, delivery, tracking, and customer support.", "Process payments, refunds, returns, and exchanges.", "Communicate order-related information.", "Respond to enquiries and resolve complaints.", "Improve products, website functionality, and customer experience.", "Prevent fraud, abuse, security incidents, and misuse.", "Comply with legal, regulatory, tax, and accounting requirements.", "Send promotional communications where permitted and subject to applicable consent and preferences."]} /></CopySection>
    <CopySection title="3. Cookies & similar technologies"><p>We may use cookies and similar technologies to keep the website functioning, remember preferences, understand website usage, improve performance, and support relevant marketing or analytics. Cookie choices may depend on the tools and settings available on the website and your browser or device.</p></CopySection>
    <CopySection title="4. Sharing information"><p>We may share relevant information with service providers who help us operate the business, such as payment processors, logistics and courier partners, technology and platform providers, analytics or marketing providers, customer-support tools, and professional advisers, where necessary and appropriate.</p><p>We may also disclose information where required by law, legal process, regulatory authority, fraud-prevention requirements, or to protect our rights, customers, property, or systems.</p></CopySection>
    <CopySection title="5. Payment information"><p>Payments may be processed by third-party payment gateways. Customers should review the applicable gateway’s privacy practices. LIVOARA does not intend to store complete card credentials such as full card numbers or CVV in its own systems.</p></CopySection>
    <CopySection title="6. Marketing communications"><p>Where permitted and subject to applicable consent requirements, we may send promotional emails, messages, or other communications. You may opt out using the unsubscribe mechanism provided or by contacting <a className="text-foreground underline underline-offset-4" href="mailto:hello@livoara.in">hello@livoara.in</a>. Transactional communications necessary to fulfil an order may still be sent.</p></CopySection>
    <CopySection title="7. Data security"><p>We use reasonable administrative, technical, and organisational safeguards intended to protect personal information against unauthorised access, misuse, alteration, disclosure, or loss. However, no internet transmission or storage system can be guaranteed to be completely secure.</p></CopySection>
    <CopySection title="8. Data retention"><p>We retain information for as long as reasonably necessary for the purposes described in this policy, including order fulfilment, customer support, accounting, tax, legal, fraud-prevention, and dispute-resolution requirements.</p></CopySection>
    <CopySection title="9. Third-party links"><p>The website may contain links to third-party websites or services. LIVOARA is not responsible for their privacy practices, and customers should review their respective policies.</p></CopySection>
    <CopySection title="10. Children’s privacy"><p>Our website is intended for general consumers and is not knowingly directed at children. We do not knowingly seek to collect personal information from children in circumstances where such collection is not permitted.</p></CopySection>
    <CopySection title="11. Privacy requests"><p>For questions, concerns, access, correction, deletion, consent withdrawal, marketing preferences, or other requests regarding personal information, contact <a className="text-foreground underline underline-offset-4" href="mailto:hello@livoara.in">hello@livoara.in</a>. We may need to verify the requester’s identity before responding.</p></CopySection>
    <CopySection title="12. Policy updates"><p>We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated effective date.</p></CopySection>
    <CopySection title="13. Contact"><p>Privacy contact: <a className="text-foreground underline underline-offset-4" href="mailto:hello@livoara.in">hello@livoara.in</a></p><p>Registered business: ARINJJOY VENTURES<br />Registered address: Kalinga Nagar, Ghatikia, Bhubaneswar, Odisha – 751003<br />GSTIN: 21ACMFA2803PIZE</p></CopySection>
  </EditorialPage>;
}

function PolicyList({ items }: { items: string[] }) {
  return <ul className="list-disc space-y-2 pl-5">{items.map((item) => <li key={item}>{item}</li>)}</ul>;
}