import { createFileRoute } from "@tanstack/react-router";
import { CopySection, EditorialPage } from "@/components/editorial-page";

const description = "Find LIVOARA shipping, delivery, returns, refunds, and exchange information.";
export const Route = createFileRoute("/shipping-returns")({ head: () => ({ meta: [{ title: "Shipping & Returns — LIVOARA" }, { name: "description", content: description }, { property: "og:title", content: "Shipping & Returns — LIVOARA" }, { property: "og:description", content: description }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ShippingPage });

function ShippingPage() {
  return <EditorialPage eyebrow="Policies & customer care" title="Shipping & Returns" intro="At LIVOARA, we aim to make delivery simple, transparent, and reliable. This page also explains the conditions and process for requesting a return, refund, or exchange.">
    <CopySection title="Policy status"><p>Effective date: 14 September 2026. Claims for damaged, defective, incorrect, or incomplete products are assessed under the eligibility and evidence requirements below. No separate product warranty is offered unless expressly stated on the product page or required by applicable law.</p></CopySection>
    <CopySection title="Shipping policy — order processing"><p>Orders are generally processed after successful payment confirmation or, for eligible COD orders, after the applicable verification or confirmation process. Processing times may vary by product, availability, location, and order volume.</p><p>Personalised or Print-on-Demand products may require additional production or processing time. The applicable timeline will be communicated on the relevant product page or at checkout wherever possible.</p></CopySection>
    <CopySection title="Delivery timeline"><p>Estimated delivery timelines are displayed or communicated based on the delivery location and available logistics service. Estimates are indicative and may vary due to courier delays, weather, public holidays, peak sale periods, service disruptions, remote-location constraints, or circumstances beyond our control.</p></CopySection>
    <CopySection title="Shipping charges"><p>Shipping charges, if applicable, will be displayed during checkout or otherwise communicated before order completion. Promotional free-shipping thresholds may be offered from time to time and may have specific terms.</p></CopySection>
    <CopySection title="Delivery address"><p>Customers are responsible for providing a complete and accurate delivery address, mobile number, and other information required for successful delivery. LIVOARA is not responsible for delays or failed delivery resulting from incorrect or incomplete information supplied by the customer.</p></CopySection>
    <CopySection title="Failed delivery / RTO"><p>If an order cannot be delivered because the customer is unavailable, refuses delivery, provides an incorrect address or phone number, does not respond to delivery attempts, or otherwise prevents successful delivery, the shipment may be returned to origin. Re-dispatch, where offered, may be subject to applicable shipping or logistics charges.</p><p>For COD orders, repeated refusal or non-acceptance may affect future COD availability.</p></CopySection>
    <CopySection title="Damaged package at delivery"><p>Customers are encouraged to inspect the outer package at delivery. If it appears materially damaged or tampered with, document the condition and contact <a className="text-foreground underline underline-offset-4" href="mailto:hello@livoara.in">hello@livoara.in</a> promptly.</p></CopySection>
    <CopySection title="Tracking"><p>Where tracking is available, tracking details will be shared through the contact information provided with the order. Tracking information may take some time to update after shipment pickup.</p></CopySection>
    <CopySection title="International shipping"><p>International shipping is not offered unless specifically stated on the website.</p></CopySection>
    <CopySection title="Return / refund request window"><p>A refund or return request is valid only if raised within <strong className="text-foreground">7 calendar days from the date the customer receives the order</strong>. Requests raised after this period may not be accepted, except where required by applicable law or where LIVOARA expressly agrees otherwise.</p></CopySection>
    <CopySection title="Mandatory unboxing video"><p>For any return, refund, or exchange request, a clear, continuous unboxing video is mandatory. The video should begin before the package is opened and clearly show the outer packaging, shipping label or order details, opening of the package, and the condition of the product and its contents.</p><p>The video helps us assess claims involving damage, missing items, incorrect products, or product condition. Where required evidence is unavailable, LIVOARA may be unable to approve the claim, subject to applicable law.</p></CopySection>
    <CopySection title="Eligible reasons"><p>Requests may be considered where the product is received damaged, defective, incorrect, incomplete or missing components, or otherwise qualifies under the applicable terms. Products that have been used, altered, washed, damaged after delivery, or returned without required components or packaging may not qualify.</p></CopySection>
    <CopySection title="Logistics charges"><p>For approved returns or refunds, the customer is responsible for applicable return logistics charges. For approved exchanges, the customer is responsible for applicable exchange logistics charges. The amount and process will be communicated by the support team before the return or exchange is arranged, where applicable.</p></CopySection>
    <CopySection title="Product condition"><p>Returned products must be in an eligible condition, with original packaging, accessories, tags, manuals, and other components where applicable. Products should not show signs of misuse, alteration, or damage caused after delivery.</p></CopySection>
    <CopySection title="How to request a return, refund, or exchange"><PolicyList items={["Email hello@livoara.in within 7 calendar days of receiving the order.", "Include the order number, registered mobile or email, product name, and reason for the request.", "Provide the mandatory unboxing video and any supporting photographs or videos requested by our team.", "Do not ship the product back independently before receiving instructions from LIVOARA.", "Our team will review the request and confirm whether it is eligible.", "If approved, follow the return or exchange instructions provided by our team."]} /></CopySection>
    <CopySection title="Inspection & approval"><p>All return, refund, and exchange requests are subject to verification. LIVOARA may inspect the returned product and supporting evidence before approving the final refund or exchange.</p></CopySection>
    <CopySection title="Refund processing"><p>Once an eligible return is received and approved, the applicable refund will be initiated through the appropriate payment method or process. The time taken to reflect may depend on the payment gateway, bank, or financial institution. Any non-refundable charges, applicable logistics charges, or other permitted deductions will be communicated as appropriate.</p></CopySection>
    <CopySection title="Exchanges"><p>Exchange requests are subject to product availability and eligibility. If the requested replacement is unavailable, LIVOARA may offer an alternative resolution, including a refund where applicable. Applicable exchange logistics charges are borne by the customer.</p></CopySection>
    <CopySection title="Non-returnable & special products"><p>Certain products may be non-returnable or subject to special conditions due to their nature, hygiene considerations, personalisation, Print-on-Demand production, or other applicable restrictions. Such restrictions will be stated on the relevant product page where applicable.</p><p>Personalised and Print-on-Demand products are created specifically for the customer and may therefore have special restrictions. If such a product arrives damaged, defective, or incorrect, contact us within 7 calendar days with the mandatory unboxing video and supporting evidence.</p></CopySection>
    <CopySection title="Consumer rights & contact"><p>Nothing in this policy is intended to limit any rights or remedies available to customers under applicable law.</p><p>Shipping, return, refund, and exchange assistance: <a className="text-foreground underline underline-offset-4" href="mailto:hello@livoara.in">hello@livoara.in</a>. Please include your order number.</p></CopySection>
  </EditorialPage>;
}

function PolicyList({ items }: { items: string[] }) {
  return <ul className="list-disc space-y-2 pl-5">{items.map((item) => <li key={item}>{item}</li>)}</ul>;
}